### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by aktech** [pravj/modified-lanyon#1]
Hi, I am using this theme here: http://blog.iamit.in/
but the tags are not working.
It works locally though. 

How these plugins can work when pushed to Github?

**Comment by pravj** [comment]
Hi @aktech,

I see that it's resolved now.
Will you please share with me, what the issue was?

I was just about to clone your instance but saw that you closed the issue.

**Comment by aktech** [comment]
I just forget, github doesn't allows jekyll plugins.
So, now I pushed the static generated files, and it works now. :)
